#ifndef OPYNETWORK_H_
#define OPYNETWORK_H_

enum
{
	ID_NETWORK_INPUTLINKLIST = 1000,
	ID_NETWORK_MAXDISTANCE = 1001,
	ID_NETWORK_MAXCONNECTIONS = 1002,
	ID_NETWORK_FIELD = 1003,
	ID_NETWORK_FIELDGROUP = 1004,
	ID_NETWORK_SCRAMBLER = 1005,
	ID_NETWORK_SCRAMBLESEED = 1006
};

#endif // OPYNETWORK_H_